shellhardener

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -52,7 +52,7 @@ BIGFONT="1080"
 
 # Get a serial number if present (eg. RPi) otherwise use MAC address from eth0
 MACHINE_UID="$(awk '/^Serial/{s='0000000' $3; print substr(s, length(s) - 7)}' /proc/cpuinfo)"
-[ -z "$MACHINE_UID" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
+[ "$MACHINE_UID" = "" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
 
 # common functions
 . /functions
@@ -65,7 +65,7 @@ progress() {
 }
 
 debug_msg() {
-  echo "$1" >&$SILENT_OUT
+  echo "$1" >&"$SILENT_OUT"
 }
 
 debug_shell() {
@@ -88,7 +88,7 @@ error() {
 
 break_after() {
   # Start debug shell after boot step $1, and all subsequent steps
-  if [ $BREAK_TRIPPED == yes ]; then
+  if [ "$BREAK_TRIPPED" == yes ]; then
     debug_shell
   else
     case $BREAK in
@@ -106,12 +106,12 @@ break_after() {
 mount_common() {
   # Common mount handler, handles block devices and filesystem images
   MOUNT_OPTIONS="-o $3"
-  [ -n "$4" ] && MOUNT_OPTIONS="-t $4 $MOUNT_OPTIONS"
+  [ "$4" != "" ] && MOUNT_OPTIONS="-t $4 $MOUNT_OPTIONS"
 
   for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
     ERR_ENV=1
 
-    mount $MOUNT_OPTIONS $1 $2 >&$SILENT_OUT 2>&1
+    mount "$MOUNT_OPTIONS" "$1" "$2" >&"$SILENT_OUT" 2>&1
     [ "$?" -eq "0" ] && ERR_ENV=0 && break
 
     usleep 1000000
@@ -125,7 +125,7 @@ get_iscsistart_options() {
   IFS_SAVE="$IFS"
   IFS=,
 
-  for arg in $1; do
+  for arg in "$1"; do
     val="${arg#*=}"
     case "$arg" in
       iscsi_initiator=*)
@@ -173,11 +173,11 @@ mount_iscsi() {
 
   if [ "$ISCSI_OPTIONS" = "auto" ]; then
     progress "Network configuration based on iBFT"
-    /usr/sbin/iscsistart -N >&$SILENT_OUT 2>&1 || error "iscsistart" "Unable to configure network"
+    /usr/sbin/iscsistart -N >&"$SILENT_OUT" 2>&1 || error "iscsistart" "Unable to configure network"
     progress "iSCSI auto connect based on iBFT"
-    /usr/sbin/iscsistart -b >&$SILENT_OUT 2>&1 || error "iscsistart" "Unable to auto connect"
+    /usr/sbin/iscsistart -b >&"$SILENT_OUT" 2>&1 || error "iscsistart" "Unable to auto connect"
   else
-    /usr/sbin/iscsistart $(get_iscsistart_options "$ISCSI_OPTIONS") >&$SILENT_OUT 2>&1 || error "iscsistart" "Unable to connect to ISCSI target"
+    /usr/sbin/iscsistart "$(get_iscsistart_options "$ISCSI_OPTIONS")" >&"$SILENT_OUT" 2>&1 || error "iscsistart" "Unable to connect to ISCSI target"
   fi
 
   mount_common "$ISCSI_DEV" "$2" "$3" "$4"
@@ -189,7 +189,7 @@ mount_nbd() {
   NBD_PORT="${1#*:}"
   NBD_DEV="/dev/nbd$NBD_DEVS"
 
-  nbd-client $NBD_SERVER $NBD_PORT $NBD_DEV >&$SILENT_OUT 2>&1 || error "nbd-client" "Could not connect to NBD server $1"
+  nbd-client "$NBD_SERVER" "$NBD_PORT" "$NBD_DEV" >&"$SILENT_OUT" 2>&1 || error "nbd-client" "Could not connect to NBD server $1"
 
   mount_common "$NBD_DEV" "$2" "$3" "$4"
 
@@ -243,7 +243,7 @@ mount_part() {
   # Substitute unique identifier if available or remove placeholder
   MOUNT_TARGET="${MOUNT_TARGET//@UID@/$MACHINE_UID}"
 
-  $MOUNT_CMD "$MOUNT_TARGET" "$2" "$3" "$4"
+  "$MOUNT_CMD" "$MOUNT_TARGET" "$2" "$3" "$4"
 }
 
 mount_sysroot() {
@@ -261,9 +261,9 @@ mount_sysroot() {
 
 # mount the specified SYSTEM file and output arch from /etc/os-release
 get_project_arch() {
-  if [ -f ${1}/etc/os-release ]; then
-    . ${1}/etc/os-release
-    echo "${LIBREELEC_ARCH}"
+  if [ -f "${1}"/etc/os-release ]; then
+    . "${1}"/etc/os-release
+    echo "$LIBREELEC_ARCH"
   fi
 }
 
@@ -282,7 +282,7 @@ is_compatible() {
     fi
   fi
 
-  return ${result}
+  return "$result"
 }
 
 # determine if the new SYSTEM file is compatible with the current SYSTEM file
@@ -294,11 +294,11 @@ check_is_compatible() {
   new_project_arch="$(get_project_arch "/update")" || return
 
   # If old or new project/arch isn't available then could be very old (pre-/etc/os-release) build - have to trust it
-  if [ -n "${old_project_arch}" -a -n "${new_project_arch}" ]; then
+  if [ "$old_project_arch" != "" -a -n "$new_project_arch" ]; then
     # If the old project/arch is not compatible with the new project/arch then abort...
-    if ! is_compatible "${old_project_arch}" "${new_project_arch}"; then
+    if ! is_compatible "$old_project_arch" "$new_project_arch"; then
       echo ""
-      echo "ERROR: $(basename "${update_filename}") is not compatible with ${old_project_arch} hardware - update cancelled."
+      echo "ERROR: $(basename "$update_filename") is not compatible with ${old_project_arch} hardware - update cancelled."
       echo ""
       echo "Current system: ${old_project_arch}"
       echo "Update  system: ${new_project_arch}"
@@ -317,12 +317,12 @@ update_file() {
     mount -o remount,rw /flash
 
     rm -f "$3"
-    StartProgress percent "Updating $1... " "$3" $(stat -t "$UPDATE_DIR/$2" | awk '{print $2}')
+    StartProgress percent "Updating $1... " "$3" "$(stat -t "$UPDATE_DIR/$2" | awk '{print $2}')"
       # use dd here with conv=fsync so that all writes are non-buffered
       # ensuring accurate progress - take the sync hit during the
       # transfer, rather than when flushing file buffers after the progress
       # meter declares the transfer already complete
-      dd if=$UPDATE_DIR/$2 of=$3 bs=1M conv=fsync 2>/dev/null
+      dd if="$UPDATE_DIR/$2" of="$3" bs=1M conv=fsync 2>/dev/null
       StopProgress
 
     # loopback file needs writable /flash all the time
@@ -340,7 +340,7 @@ update_partition() {
     StartProgress spinner "Updating $1... "
       result="$(dd if="$UPDATE_DIR/$2" of="$3" 2>&1)"
       StopProgress "done"
-    echo "${result}"
+    echo "$result"
   fi
 }
 
@@ -350,12 +350,12 @@ update_bootloader() {
   export BOOT_ROOT="/flash"
   export SYSTEM_ROOT="/update"
 
-  if [ -f $SYSTEM_ROOT/usr/share/bootloader/update.sh ]; then
+  if [ -f "$SYSTEM_ROOT"/usr/share/bootloader/update.sh ]; then
     StartProgress spinner "Updating Boot Files... "
-      result="$(sh $SYSTEM_ROOT/usr/share/bootloader/update.sh 2>&1)"
+      result="$(sh "$SYSTEM_ROOT"/usr/share/bootloader/update.sh 2>&1)"
       sync
       StopProgress "done"
-    [ -n "${result}" ] && echo "${result}"
+    [ "$result" != "" ] && echo "$result"
   fi
 }
 
@@ -365,7 +365,7 @@ set_consolefont() {
   progress "Set console font"
   if [ -e /dev/fb0 ]; then
     vres="$(fbset 2>/dev/null | awk '/geometry/ { print $3 }')"
-    if [ $vres -gt "$BIGFONT" ]; then
+    if [ "$vres" -gt "$BIGFONT" ]; then
       setfont -C /dev/tty0 ter-v32b.psf
     fi
   fi
@@ -389,7 +389,7 @@ load_splash() {
 
         # Try setting a custom framebuffer resolution
         if [ ! "${SWITCH_FRAMEBUFFER:-yes}" = "yes" ]; then
-          fbset -g $SWITCH_FRAMEBUFFER 2>/dev/null && set_default_res=no
+          fbset -g "$SWITCH_FRAMEBUFFER" 2>/dev/null && set_default_res=no
         fi
 
         # Set a default resolution if required
@@ -404,24 +404,24 @@ load_splash() {
       fi
 
       # Select splash image based on current native resolution
-      if [ -z "$SPLASHIMAGE" ]; then
+      if [ "$SPLASHIMAGE" = "" ]; then
         vres="$(fbset 2>/dev/null | awk '/geometry/ { print $3 }')"
 
-        for s in /flash/oemsplash-${vres}.png \
+        for s in /flash/oemsplash-"$vres".png \
                  /flash/oemsplash-1080.png \
                  /flash/oemsplash.png \
-                 /splash/splash-${vres}.png \
+                 /splash/splash-"$vres".png \
                  /splash/splash-1080.png \
                  ; do
-          if [ -f "${s}" ]; then
-            SPLASHIMAGE="${s}"
+          if [ -f "$s" ]; then
+            SPLASHIMAGE="$s"
             break
           fi
         done
       fi
 
-      if [ -n "$SPLASHIMAGE" -a -f "$SPLASHIMAGE" ]; then
-        ply-image $SPLASHIMAGE > /dev/null 2>&1
+      if [ "$SPLASHIMAGE" != "" -a -f "$SPLASHIMAGE" ]; then
+        ply-image "$SPLASHIMAGE" > /dev/null 2>&1
       fi
 
       debug_msg "Framebuffer vertical res: $vres"
@@ -460,7 +460,7 @@ force_fsck() {
   if [ $? -ne 0 -o $? -gt 128 ]; then
     echo "Repairing filesystem..."
     echo ""
-    /usr/sbin/fsck -T -M -y $RUN_FSCK_DISKS
+    /usr/sbin/fsck -T -M -y "$RUN_FSCK_DISKS"
     FSCK_RET=$?
     if [ $(( $FSCK_RET & 8 )) -eq 8 ]; then
       # fubar
@@ -486,17 +486,17 @@ check_disks() {
     progress "Checking disk(s): $RUN_FSCK_DISKS"
     echo "Checking disk(s): $RUN_FSCK_DISKS" >/dev/kmsg
     for i in 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0; do
-      /usr/sbin/fsck -T -M -p -a $RUN_FSCK_DISKS >/dev/fsck.latest 2>&1
+      /usr/sbin/fsck -T -M -p -a "$RUN_FSCK_DISKS" >/dev/fsck.latest 2>&1
       FSCK_RET=$?
       cat /dev/fsck.latest >>/dev/fsck.log
 
       # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
-      if [ $FSCK_RET -ge 16 ]; then
+      if [ "$FSCK_RET" -ge 16 ]; then
         progress "General error, continuing..."
         break
       elif [ $(( $FSCK_RET & 8 )) -eq 8 ]; then
         # device not found
-        if [ $i -eq 0 ]; then
+        if [ "$i" -eq 0 ]; then
           progress "Device not found, continuing..."
         else
           usleep 500000
@@ -512,14 +512,14 @@ check_disks() {
         # filesystem errors corrected
         progress "Filesystem errors corrected , continuing..."
         break
-      elif [ $FSCK_RET -eq 0 ]; then
+      elif [ "$FSCK_RET" -eq 0 ]; then
         # no errors found
         progress "No filesystem errors found, continuing..."
         break
       fi
     done
     while read line; do
-      [ -n "$line" ] && echo "fsck: ${line::160}" >/dev/kmsg
+      [ "$line" != "" ] && echo "fsck: ${line::160}" >/dev/kmsg
     done </dev/fsck.latest
     rm -f /dev/fsck.latest
   fi
@@ -536,12 +536,12 @@ wakeonlan() {
     return 0
   fi
 
-  if [ -n "$wol_ip" -a -n "$wol_mac" -a -n "$wol_wait" ]; then
+  if [ "$wol_ip" != "" -a -n "$wol_mac" -a -n "$wol_wait" ]; then
     progress "Sending Magic Packet (WOL) if needed"
 
     if ! ping -q -c 2 "$wol_ip" &>/dev/null; then
       ether-wake "$wol_mac"
-      StartProgress countdown "WOL magic packet sent to $wol_ip, waiting $wol_wait seconds... " $wol_wait "done"
+      StartProgress countdown "WOL magic packet sent to $wol_ip, waiting $wol_wait seconds... " "$wol_wait" "done"
     fi
   fi
 }
@@ -583,12 +583,12 @@ mount_storage() {
 
   wakeonlan
 
-  if [ -n "$disk" ]; then
-    if [ -n "$OVERLAY" ]; then
+  if [ "$disk" != "" ]; then
+    if [ "$OVERLAY" != "" ]; then
       OVERLAY_DIR=$(cat /sys/class/net/eth0/address | tr -d :)
 
       mount_part "$disk" "/storage" "rw,noatime"
-      mkdir -p /storage/$OVERLAY_DIR
+      mkdir -p /storage/"$OVERLAY_DIR"
       umount /storage
 
       # split $disk into $target,$options so we can append $OVERLAY_DIR
@@ -616,7 +616,7 @@ mount_storage() {
 update_bootmenu() {
   local crnt_default
 
-  if [ -n "$SYSLINUX_DEFAULT" -a -f /flash/syslinux.cfg ]; then
+  if [ "$SYSLINUX_DEFAULT" != "" -a -f /flash/syslinux.cfg ]; then
     if grep -q "^LABEL $SYSLINUX_DEFAULT\$" /flash/syslinux.cfg; then
       crnt_default="$(awk '/^DEFAULT/ {print $2}' /flash/syslinux.cfg)"
       if [ ! "$crnt_default" = "$SYSLINUX_DEFAULT" ]; then
@@ -631,7 +631,7 @@ update_bootmenu() {
     fi
   fi
 
-  if [ -n "$GRUB_DEFAULT" -a -f /flash/EFI/BOOT/grub.cfg ]; then
+  if [ "$GRUB_DEFAULT" != "" -a -f /flash/EFI/BOOT/grub.cfg ]; then
     if grep -q "^menuentry \"$GRUB_DEFAULT\"" /flash/EFI/BOOT/grub.cfg; then
       crnt_default="$(awk '/^set default/ {print substr($2,9,19)}' /flash/EFI/BOOT/grub.cfg)"
       if [ ! "$crnt_default" = "\"$GRUB_DEFAULT\"" ]; then
@@ -671,22 +671,22 @@ do_cleanup() {
     umount /update
   fi
 
-  if [ -d $UPDATE_ROOT/.tmp/mnt ]; then
-    if mountpoint -q $UPDATE_ROOT/.tmp/mnt ; then
+  if [ -d "$UPDATE_ROOT"/.tmp/mnt ]; then
+    if mountpoint -q "$UPDATE_ROOT"/.tmp/mnt ; then
       # busybox umount deletes loop device automatically
-      umount $UPDATE_ROOT/.tmp/mnt
+      umount "$UPDATE_ROOT"/.tmp/mnt
     fi
 
-    [ -n $LOOP ] && losetup -d $LOOP &>/dev/null
+    [ "$LOOP" != "" ] && losetup -d "$LOOP" &>/dev/null
   fi
 
   [ -f "$UPDATE_TAR" ] && rm -f "$UPDATE_TAR" &>/dev/null
   [ -f "$UPDATE_IMG_GZ" ] && rm -f "$UPDATE_IMG_GZ" &>/dev/null
   [ -f "$UPDATE_IMG" ] && rm -f "$UPDATE_IMG" &>/dev/null
 
-  rm -rf $UPDATE_ROOT/.tmp &>/dev/null
-  rm -rf $UPDATE_ROOT/[0-9a-zA-Z]* &>/dev/null
-  rm -f  $UPDATE_ROOT/.nocheck $UPDATE_ROOT/.nocompat &>/dev/null
+  rm -rf "$UPDATE_ROOT"/.tmp &>/dev/null
+  rm -rf "$UPDATE_ROOT"/[0-9a-zA-Z]* &>/dev/null
+  rm -f  "$UPDATE_ROOT"/.nocheck "$UPDATE_ROOT"/.nocompat &>/dev/null
 
   sync
 
@@ -711,7 +711,7 @@ check_update() {
     return 0
   fi
 
-  if [ -d $UPDATE_DIR/.tmp ]; then
+  if [ -d "$UPDATE_DIR"/.tmp ]; then
     echo "Failed update detected - performing recovery."
     echo ""
     do_cleanup
@@ -719,7 +719,7 @@ check_update() {
     return 0
   fi
 
-  mkdir -p $UPDATE_DIR/.tmp &>/dev/null
+  mkdir -p "$UPDATE_DIR"/.tmp &>/dev/null
   sync
 
   echo "UPDATE IN PROGRESS"
@@ -733,10 +733,10 @@ check_update() {
     echo "Found new .tar archive"
     UPDATE_FILENAME="$UPDATE_TAR"
     StartProgress spinner "Extracting contents of archive... "
-      tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp 1>/dev/null 2>/tmp/tarresult.txt || TARRESULT="1"
+      tar -xf "$UPDATE_TAR" -C "$UPDATE_DIR"/.tmp 1>/dev/null 2>/tmp/tarresult.txt || TARRESULT="1"
 
-    if [ "${TARRESULT}" -eq "0" ]; then
-      mv $UPDATE_DIR/.tmp/*/target/* $UPDATE_DIR &>/dev/null
+    if [ "$TARRESULT" -eq "0" ]; then
+      mv "$UPDATE_DIR"/.tmp/*/target/* "$UPDATE_DIR" &>/dev/null
       sync
       StopProgress "done"
     else
@@ -752,7 +752,7 @@ check_update() {
       return 0
     fi
   elif [ -f "$UPDATE_IMG_GZ" -o -f "$UPDATE_IMG" ]; then
-    mkdir -p $UPDATE_DIR/.tmp/mnt &>/dev/null
+    mkdir -p "$UPDATE_DIR"/.tmp/mnt &>/dev/null
     IMG_FILE="$UPDATE_DIR/.tmp/update.img"
     GZRESULT="0"
 
@@ -760,11 +760,11 @@ check_update() {
       echo "Found new compressed image file"
       UPDATE_FILENAME="$UPDATE_IMG_GZ"
       StartProgress spinner "Decompressing image file... "
-        gunzip -d -c "$UPDATE_IMG_GZ" 1>$IMG_FILE 2>/tmp/gzresult.txt || GZRESULT="1"
+        gunzip -d -c "$UPDATE_IMG_GZ" 1>"$IMG_FILE" 2>/tmp/gzresult.txt || GZRESULT="1"
         sync
-        [ "${GZRESULT}" -eq "0" ] && StopProgress "OK" || StopProgress "FAILED"
+        [ "$GZRESULT" -eq "0" ] && StopProgress "OK" || StopProgress "FAILED"
 
-      if [ "${GZRESULT}" -eq "1" ]; then
+      if [ "$GZRESULT" -eq "1" ]; then
         echo "Failed to decompress image file!"
         echo "gunzip result: '$(cat /tmp/gzresult.txt)'"
 
@@ -777,20 +777,20 @@ check_update() {
     else
       echo "Found new image file"
       UPDATE_FILENAME="$UPDATE_IMG"
-      mv "$UPDATE_IMG" $IMG_FILE
+      mv "$UPDATE_IMG" "$IMG_FILE"
     fi
 
     LOOP=$(losetup -f)
-    LOOP_NUM=$(echo $LOOP | sed 's|/dev/loop||')
-    mknod $LOOP b 7 $LOOP_NUM &>/dev/null
-    losetup $LOOP $IMG_FILE
+    LOOP_NUM=$(echo "$LOOP" | sed 's|/dev/loop||')
+    mknod "$LOOP" b 7 "$LOOP_NUM" &>/dev/null
+    losetup "$LOOP" "$IMG_FILE"
 
     # check for MBR partititon
-    OFFSET=$(fdisk -u -l $LOOP 2>/dev/null | awk '/^[ ]*Device/{part=1; next}; part{if ($2 == "*") {print $5} else {print $4} ; exit}')
-    if [ -z "$OFFSET" ]; then
+    OFFSET=$(fdisk -u -l "$LOOP" 2>/dev/null | awk '/^[ ]*Device/{part=1; next}; part{if ($2 == "*") {print $5} else {print $4} ; exit}')
+    if [ "$OFFSET" = "" ]; then
       # check for GPT partititon
-      OFFSET=$(fdisk -u -l $LOOP 2>/dev/null | awk '/^Number/{part=1; next}; part{print $2; exit}')
-      if [ -z "$OFFSET" ]; then
+      OFFSET=$(fdisk -u -l "$LOOP" 2>/dev/null | awk '/^Number/{part=1; next}; part{print $2; exit}')
+      if [ "$OFFSET" = "" ]; then
         echo "Could not find a valid system partition in image file!"
         do_cleanup
         StartProgress countdown "Normal startup in 10s... " 10 "NOW"
@@ -798,16 +798,16 @@ check_update() {
       fi
     fi
 
-    SECTOR_SIZE=$(cat /sys/devices/virtual/block/loop${LOOP_NUM}/queue/hw_sector_size)
-    losetup -d $LOOP
+    SECTOR_SIZE=$(cat /sys/devices/virtual/block/loop"$LOOP_NUM"/queue/hw_sector_size)
+    losetup -d "$LOOP"
     sync
 
     OFFSET=$(($OFFSET * $SECTOR_SIZE))
 
     # use losetup because busybox mount does not support the -o offset option
     echo "Mounting system partition..."
-    losetup -o $OFFSET $LOOP $IMG_FILE
-    mount -o ro,loop $LOOP $UPDATE_DIR/.tmp/mnt
+    losetup -o "$OFFSET" "$LOOP" "$IMG_FILE"
+    mount -o ro,loop "$LOOP" "$UPDATE_DIR"/.tmp/mnt
 
     # don't make temporary files but instead copy
     # directly from mountpoint to /flash
@@ -906,7 +906,7 @@ check_update() {
   TMP_SIZE=$((OLD_KERNEL + OLD_SYSTEM + FLASH_FREE - NEW_KERNEL - NEW_SYSTEM))
   FLASH_FREE_MIN=$((FLASH_FREE_MIN * 1024 * 1024))
 
-  if [ $TMP_SIZE -ge $FLASH_FREE_MIN ]; then
+  if [ "$TMP_SIZE" -ge "$FLASH_FREE_MIN" ]; then
     echo "Checking size: OK"
   else
     echo "Checking size: FAILED"
@@ -969,7 +969,7 @@ clear
 hidecursor
 
 # parse command line arguments
-for arg in $(cat /proc/cmdline); do
+for arg in "$(cat /proc/cmdline)"; do
   case $arg in
     BOOT_IMAGE=*)
       IMAGE_KERNEL="${arg#*=}"
@@ -1089,8 +1089,8 @@ for BOOT_STEP in \
     mount_storage \
     check_update \
     prepare_sysroot; do
-  $BOOT_STEP
-  [ -n "$DEBUG" ] && break_after $BOOT_STEP
+  "$BOOT_STEP"
+  [ "$DEBUG" != "" ] && break_after "$BOOT_STEP"
 done
 
 BOOT_STEP=final
@@ -1098,11 +1098,11 @@ BOOT_STEP=final
 # log if booting from usb / removable storage
 STORAGE=$(cat /proc/mounts | grep " /sysroot/storage " | awk '{print $1}' | awk -F '/' '{print $3}')
 FLASH=$(cat /proc/mounts | grep " /sysroot/flash " | awk '{print $1}' | awk -F '/' '{print $3}')
-for i in $STORAGE $FLASH ; do
-  if [ -n "$i" ]; then
+for i in "$STORAGE" "$FLASH" ; do
+  if [ "$i" != "" ]; then
     removable="/sys/class/block/*/$i/../removable"
-    if [ -e $removable ]; then
-      if [ "$(cat $removable 2>/dev/null)" = "1" ]; then
+    if [ -e "$removable" ]; then
+      if [ "$(cat "$removable" 2>/dev/null)" = "1" ]; then
         echo "### BIG FAT WARNING" > /dev/kmsg
         echo "### $i is removable. suspend/resume may not work" > /dev/kmsg
       fi
@@ -1138,6 +1138,6 @@ if [ "$STORAGE_NETBOOT" = "yes" ]; then
 fi
 
 # switch to new sysroot and start real init
-exec /usr/bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS
+exec /usr/bin/busybox switch_root /sysroot /usr/lib/systemd/systemd "$INIT_ARGS"
 
 error "switch_root" "Error in initramfs. Could not switch to new root"
diff --git a/scripts/create_addon b/scripts/create_addon
--- a/scripts/create_addon
+++ b/scripts/create_addon
@@ -41,7 +41,7 @@ EXAMPLE
        build all, but not binary
        > ./script/create_addon all -binary
 EOF
-  exit ${1:-0}
+  exit "${1:-0}"
 }
 
 # Get list of addon packages
@@ -59,37 +59,37 @@ get_addons() {
 
   exit() { exited=1; }
 
-  for pkgpath in $(cat "${_CACHE_PACKAGE_LOCAL}" "${_CACHE_PACKAGE_GLOBAL}" | grep -E "${paths}"); do
-    if [ -n "${filter}" ]; then
+  for pkgpath in "$(cat "$_CACHE_PACKAGE_LOCAL" "$_CACHE_PACKAGE_GLOBAL" | grep -E "$paths")"; do
+    if [ "$filter" != "" ]; then
       [[ ${pkgpath} =~ ^.*/${filter}@?+?@ ]] || continue
     fi
 
     exited=0
     source_package "${pkgpath%%@*}/package.mk" &>/dev/null
-    [ ${exited} -eq 1 ] && continue
+    [ "$exited" -eq 1 ] && continue
 
     validpkg="no"
     VERIFY_FAIL=
     # Should only build embedded addons when they are explictly specified in the addon list
-    if [ "${PKG_IS_ADDON}" = "embedded" ]; then
-      if [ -n "${filter}" ]; then
+    if [ "$PKG_IS_ADDON" = "embedded" ]; then
+      if [ "$filter" != "" ]; then
         verify_addon && validpkg="yes"
       fi
-    elif [ "${PKG_IS_ADDON}" = "yes" ]; then
+    elif [ "$PKG_IS_ADDON" = "yes" ]; then
       verify_addon && validpkg="yes"
     fi
 
-    if [ "${validpkg}" = "yes" ]; then
-      echo "${PKG_NAME}"
+    if [ "$validpkg" = "yes" ]; then
+      echo "$PKG_NAME"
       count=$((count + 1))
-    elif [ -n "${VERIFY_FAIL}" -a -n "${filter}" ]; then
-      echo "$(print_color CLR_ERROR "${PKG_NAME}"): ${VERIFY_FAIL}" >&2
+    elif [ "$VERIFY_FAIL" != "" -a -n "$filter" ]; then
+      echo "$(print_color CLR_ERROR "$PKG_NAME"): ${VERIFY_FAIL}" >&2
     fi
   done
 
   unset -f exit
 
-  if [ ${count} -eq 0 -a -n "${filter}" ]; then
+  if [ "$count" -eq 0 -a -n "$filter" ]; then
     echo  "$(print_color CLR_ERROR "ERROR: no addons matched for filter ${filter}")" >&2
     echo  "For more information type: ./scripts/create_addon --help" >&2
     die
@@ -98,25 +98,25 @@ get_addons() {
 
 # Return 0 if package is a suitable addon, 1 otherwise
 verify_addon() {
-  if [ -n "${PKG_ARCH}" ]; then
+  if [ "$PKG_ARCH" != "" ]; then
     VERIFY_FAIL="Incompatible arch: \"${TARGET_ARCH}\" not in [ ${PKG_ARCH} ]"
-    listcontains "${PKG_ARCH}" "!${TARGET_ARCH}" && return 1
-    listcontains "${PKG_ARCH}" "${TARGET_ARCH}" || listcontains "${PKG_ARCH}" "any" || return 1
+    listcontains "$PKG_ARCH" "!${TARGET_ARCH}" && return 1
+    listcontains "$PKG_ARCH" "$TARGET_ARCH" || listcontains "$PKG_ARCH" "any" || return 1
   fi
 
-  if [ -n "${PKG_ADDON_PROJECTS}" ]; then
-    [ "${DEVICE}" = "RPi" ] && _DEVICE="RPi1" || _DEVICE="${DEVICE}"
+  if [ "$PKG_ADDON_PROJECTS" != "" ]; then
+    [ "$DEVICE" = "RPi" ] && _DEVICE="RPi1" || _DEVICE="$DEVICE"
 
     VERIFY_FAIL="Incompatible project or device: \"${_DEVICE:-${PROJECT}}\" not in [ ${PKG_ADDON_PROJECTS} ]"
 
-    if listcontains "${PKG_ADDON_PROJECTS}" "!${_DEVICE:-${PROJECT}}" ||
-       listcontains "${PKG_ADDON_PROJECTS}" "!${PROJECT}"; then
+    if listcontains "$PKG_ADDON_PROJECTS" "!${_DEVICE:-${PROJECT}}" ||
+       listcontains "$PKG_ADDON_PROJECTS" "!${PROJECT}"; then
       return 1
     fi
 
-    if ! listcontains "${PKG_ADDON_PROJECTS}" "${_DEVICE:-${PROJECT}}" &&
-       ! listcontains "${PKG_ADDON_PROJECTS}" "${PROJECT}" &&
-       ! listcontains "${PKG_ADDON_PROJECTS}" "any"; then
+    if ! listcontains "$PKG_ADDON_PROJECTS" "${_DEVICE:-${PROJECT}}" &&
+       ! listcontains "$PKG_ADDON_PROJECTS" "$PROJECT" &&
+       ! listcontains "$PKG_ADDON_PROJECTS" "any"; then
       return 1
     fi
   fi
@@ -130,7 +130,7 @@ if [ $# -eq 0 ]; then
 fi
 
 # check environment and configure toolchains
-${SCRIPTS}/checkdeps
+"$SCRIPTS"/checkdeps
 
 ( setup_toolchain host )
 setup_toolchain target
@@ -146,21 +146,21 @@ while [ $# -gt 0 ]; do
     --help)         usage 0;;
     --show-only)    show_only="yes";;
     --*)            usage 1;;
-    -*)             addons_drop+=" $(get_addons ${1:1})";;
-    *)              addons+=" $(get_addons ${1})";;
+    -*)             addons_drop+=" $(get_addons "${1:1}")";;
+    *)              addons+=" $(get_addons "${1}")";;
   esac
   shift
 done
 
 # Build a new list containing only those addons we want to build
 wanted_addons=
-for addon in $(echo ${addons} | tr ' ' '\n' | sort -u); do
-  listcontains "${addons_drop}" "${addon}" || wanted_addons+=" ${addon}"
+for addon in "$(echo "$addons" | tr ' ' '\n' | sort -u)"; do
+  listcontains "$addons_drop" "$addon" || wanted_addons+=" ${addon}"
 done
 
-if [ "${show_only}" = "yes" ]; then
-  for addon in ${wanted_addons}; do
-    echo ${addon}
+if [ "$show_only" = "yes" ]; then
+  for addon in "$wanted_addons"; do
+    echo "$addon"
   done
   exit 0
 fi
@@ -174,11 +174,11 @@ elif [ -f "${THREAD_CONTROL}/addons.failed" ]; then
   echo >&2
   print_color CLR_ERROR "FAILED ADDONS:\n" >&2
   while read -r addon logfile; do
-    if [ -n "${addon}" ]; then
-      if [ -n "${logfile}" ]; then
-        echo "    $(print_color CLR_ERROR "${addon}"): ${logfile}" >&2
+    if [ "$addon" != "" ]; then
+      if [ "$logfile" != "" ]; then
+        echo "    $(print_color CLR_ERROR "$addon"): ${logfile}" >&2
       else
-        echo "    $(print_color CLR_ERROR "${addon}")" >&2
+        echo "    $(print_color CLR_ERROR "$addon")" >&2
       fi
     fi
   done < "${THREAD_CONTROL}/addons.failed"
diff --git a/tools/distro-tool b/tools/distro-tool
--- a/tools/distro-tool
+++ b/tools/distro-tool
@@ -7,7 +7,7 @@ set -e
 
 export NOONEXIT=yes
 
-[ -z "${DEBUG_LOG}" ] && DEBUG_LOG=/tmp/distro-tool.log
+[ "$DEBUG_LOG" = "" ] && DEBUG_LOG=/tmp/distro-tool.log
 
 LIBREELEC_DIR=$HOME/LibreELEC.tv
 TARGET_DIR=$HOME/sources
@@ -695,11 +695,11 @@ if __name__ == "__main__":
     raise
 '
 
-[ -z "${PROJECT}" ] && PROJECT=Generic
-[ -z "${ARCH}" ]    && ARCH=x86_64
+[ "$PROJECT" = "" ] && PROJECT=Generic
+[ "$ARCH" = "" ]    && ARCH=x86_64
 
 help() {
-  [ -n "$1" ] && echo -e "ERROR: Unknown argument [$1]\n"
+  [ "$1" != "" ] && echo -e "ERROR: Unknown argument [$1]\n"
   cat <<EOF
 Usage: $(basename $0) -d|--download <path> [-t|--target <path>] [-l|--libreelec <path>]
            [-m|--mirror] [-s|--source] [-a|-all] [-p|--package <package_name> [-r|--revision <revision>]]
@@ -738,14 +738,14 @@ EOF
 }
 
 get_libreelec_branch() {
-  cd $LIBREELEC_DIR
+  cd "$LIBREELEC_DIR"
   git rev-parse --abbrev-ref HEAD
 }
 
 # 1: LibreELEC variable, eg. LIBREELEC_VERSION
 get_libreelec_option() {
   local variable="$1"
-  cd $LIBREELEC_DIR
+  cd "$LIBREELEC_DIR"
   source config/options ""
   echo "${!variable}"
 }
@@ -756,13 +756,13 @@ generate_work() {
   local workfile_o
   local tcount=0
 
-  [ ${PROGRESS} = yes ] && echo -en "Acquiring packages...\r" >&2
+  [ "$PROGRESS" = yes ] && echo -en "Acquiring packages...\r" >&2
 
-  packages="$(get_packages "${package_name}" "${path_filter}")"
-  pcount="$(echo "${packages}" | wc -l)"
+  packages="$(get_packages "$package_name" "$path_filter")"
+  pcount="$(echo "$packages" | wc -l)"
 
-  if [ -n "${package_name}" -a -z "${packages}" ]; then
-    if [ -n "${path_filter}" ]; then
+  if [ "$package_name" != "" -a -z "$packages" ]; then
+    if [ "$path_filter" != "" ]; then
       echo "ERROR: ${package_name} is not a valid package when using filter ${path_filter} - package.mk does not exist" >&2
     else
       echo "ERROR: ${package_name} is not a valid package - package.mk does not exist" >&2
@@ -770,14 +770,14 @@ generate_work() {
     exit 1
   fi
 
-  rm -f ${WORKFILES_I}.* ${WORKFILES_O}.*
+  rm -f "$WORKFILES_I".* "$WORKFILES_O".*
 
   # Distribute packages across workers
   tcount=0
-  for package_name in ${packages}; do
+  for package_name in "$packages"; do
     tcount=$((tcount + 1))
-    [ ${tcount} -gt ${WORKER_MAX} ] && tcount=1
-    echo "$package_name" >>$(printf "%s.%02d" "${WORKFILES_I}" ${tcount})
+    [ "$tcount" -gt "$WORKER_MAX" ] && tcount=1
+    echo "$package_name" >>"$(printf "%s.%02d" "$WORKFILES_I" "$tcount")"
   done
 
   # Generate workload using multiple "threads" (cores, hopefully...)
@@ -787,8 +787,8 @@ generate_work() {
 
   while [ : ]; do
     tcount=$((tcount + 1))
-    [ ${tcount} -gt ${WORKER_MAX} ] && break
-    generate_work_worker ${pcount} ${tcount} ${revision} &
+    [ "$tcount" -gt "$WORKER_MAX" ] && break
+    generate_work_worker "$pcount" "$tcount" "$revision" &
   done
   wait
 
@@ -799,48 +799,48 @@ generate_work() {
   tcount=0
   while [ : ]; do
     tcount=$((tcount + 1))
-    [ ${tcount} -gt ${WORKER_MAX} ] && break
-    workfile_o=$(printf "%s.%02d" "${WORKFILES_O}" ${tcount})
-    if [ -s ${workfile_o} ]; then
-      [ ${tcount} -ne 1 ] && echo ","
+    [ "$tcount" -gt "$WORKER_MAX" ] && break
+    workfile_o=$(printf "%s.%02d" "$WORKFILES_O" "$tcount")
+    if [ -s "$workfile_o" ]; then
+      [ "$tcount" -ne 1 ] && echo ","
       # Strip comma from line of file - not valid if this is the last file
-      sed '$ s/  },/  }/' ${workfile_o}
+      sed '$ s/  },/  }/' "$workfile_o"
     fi
   done
   echo "]"
 
   # Clean up
-  rm -f ${WORKFILES_I}.* ${WORKFILES_O}.*
+  rm -f "$WORKFILES_I".* "$WORKFILES_O".*
 }
 
 generate_work_worker() {
   local pcount=$1 worker="$2" revision="$3"
-  local workfile_i="$(printf "%s.%02d" "${WORKFILES_I}" ${worker})"
-  local workfile_o="$(printf "%s.%02d" "${WORKFILES_O}" ${worker})"
+  local workfile_i="$(printf "%s.%02d" "$WORKFILES_I" "$worker")"
+  local workfile_o="$(printf "%s.%02d" "$WORKFILES_O" "$worker")"
   local wanted_vars="PKG_NAME PKG_VERSION PKG_URL PKG_SHA256 PKG_DIR PKG_SECTION PKG_IS_ADDON PKG_SOURCE_NAME"
   local package_name var comma PKG_URL PKG_SOURCE_NAME PKG_VERSION PKG_IS_ADDON
 
-  [ -f "${workfile_i}" ] || return 0
+  [ -f "$workfile_i" ] || return 0
   (
     # Override exit function so that packages calling exit don't terminate this sub-shell
     exit() {
       :
     }
 
-    cd $LIBREELEC_DIR
+    cd "$LIBREELEC_DIR"
 
     source config/options ""
 
     while read -r package_name; do
-      [ ${PROGRESS} = yes ] && progress ${pcount}
+      [ "$PROGRESS" = yes ] && progress "$pcount"
 
-      source_package ${package_name} &>/dev/null || true
-      [ -z "${PKG_DIR}" ] && continue
+      source_package "$package_name" &>/dev/null || true
+      [ "$PKG_DIR" = "" ] && continue
 
-      if [ -n "${revision}" ]; then
+      if [ "$revision" != "" ]; then
         PKG_URL="${PKG_URL/${PKG_VERSION}/${revision}}"
         PKG_SOURCE_NAME="${PKG_SOURCE_NAME/${PKG_VERSION}/${revision}}"
-        PKG_VERSION="${revision}"
+        PKG_VERSION="$revision"
         PKG_SHA256=
       fi
 
@@ -848,18 +848,18 @@ generate_work_worker() {
       [[ ${PKG_DIR/${LIBREELEC_DIR}/} =~ ^/packages/addons/.* ]] && PKG_IS_ADDON=Yes
       [[ ${PKG_DIR/${LIBREELEC_DIR}/} =~ ^/packages/mediacenter/kodi-binary-addons/.* ]] && PKG_IS_ADDON=Yes
 
-      echo "  {" >>${workfile_o}
-      for var in ${wanted_vars}; do
-        [ "${var}" != "PKG_SOURCE_NAME" ] && comma="," || comma=
-        echo "    \"${var}\": \"${!var}\"${comma}" >>${workfile_o}
+      echo "  {" >>"$workfile_o"
+      for var in "$wanted_vars"; do
+        [ "$var" != "PKG_SOURCE_NAME" ] && comma="," || comma=
+        echo "    \"${var}\": \"${!var}\"${comma}" >>"$workfile_o"
       done
-      echo "  }," >>${workfile_o}
-    done < ${workfile_i}
+      echo "  }," >>"$workfile_o"
+    done < "$workfile_i"
   )
 }
 
 check_exists() {
-  if [ -z "${!1}" ]; then
+  if [ "${!1}" = "" ]; then
     echo "ERROR: ${1} must not be undefined"
     return 1
   fi
@@ -871,7 +871,7 @@ check_exists() {
 }
 
 get_abs_path() {
-  echo "$(readlink -f $1)"
+  echo "$(readlink -f "$1")"
 }
 
 get_package_path() {
@@ -883,24 +883,24 @@ get_packages() {
   local anchor="@?+?@"
 
   (
-    cd $LIBREELEC_DIR
+    cd "$LIBREELEC_DIR"
 
     # Generate package caches...
     source config/options ""
 
     cache_data="${BUILD}/.cache_package_global ${BUILD}/.cache_package_local"
 
-    if [ -n "${path_filter}" ]; then
-      if [ -n "${package_name}" ]; then
-        grep -F "/${path_filter}/" ${cache_data} | grep -F "/${package_name}${anchor}"
+    if [ "$path_filter" != "" ]; then
+      if [ "$package_name" != "" ]; then
+        grep -F "/${path_filter}/" "$cache_data" | grep -F "/${package_name}${anchor}"
       else
-        grep -F "/${path_filter}/" ${cache_data}
+        grep -F "/${path_filter}/" "$cache_data"
       fi
     else
-      if [ -n "${package_name}" ]; then
-        grep -F "/${package_name}${anchor}" ${cache_data}
+      if [ "$package_name" != "" ]; then
+        grep -F "/${package_name}${anchor}" "$cache_data"
       else
-        cat ${cache_data}
+        cat "$cache_data"
       fi
     fi
   ) | sed "s#${anchor}\$##g;s#/# #g" | awk '{print $NF}' | sort -u
@@ -909,35 +909,35 @@ get_packages() {
 }
 
 init_progress() {
-  echo 0 > ${LOCKFILE}
+  echo 0 > "$LOCKFILE"
 }
 
 progress() {
   local count
   (
     flock -x 9
-    count=$(($(< ${LOCKFILE}) + 1))
-    echo "${count}" >${LOCKFILE}
-    printf "Generating workload... %3d%% (%d of %d)\r" $((count * 100 / $1)) ${count} $1 >&2
-  ) 9< "${LOCKFILE}"
+    count=$(($(< "$LOCKFILE") + 1))
+    echo "$count" >"$LOCKFILE"
+    printf "Generating workload... %3d%% (%d of %d)\r" $((count * 100 / $1)) "$count" "$1" >&2
+  ) 9< "$LOCKFILE"
 }
 
 end_progress() {
-  rm -f ${LOCKFILE}
+  rm -f "$LOCKFILE"
   printf "\033[K\r" >&2
 }
 
 exec_worker_prog() {
-  echo "${PYTHON_PROG}" >/tmp/distro-tool.py
-  python3 /tmp/distro-tool.py "${DOWNLOAD_DIR}" "${TARGET_DIR}" "${DISTRO_SOURCE}" "${DISTRO_MIRROR}" \
-                              "${IS_MIRROR}" "${IGNORE_ERRORS}" "${DRY_RUN}" "${CHECK_NEWER}" \
-                              "${PROGRESS}" "${WORKER_THREADS}" "${GIT_USERNAME}" "${GIT_PASSWORD}" \
-                              "${CHECK_FILTER_CLASS}" "${CHECK_FILTER_TYPE}" ${VERIFY_CHECKSUM} "${VERBOSE}"
+  echo "$PYTHON_PROG" >/tmp/distro-tool.py
+  python3 /tmp/distro-tool.py "$DOWNLOAD_DIR" "$TARGET_DIR" "$DISTRO_SOURCE" "$DISTRO_MIRROR" \
+                              "$IS_MIRROR" "$IGNORE_ERRORS" "$DRY_RUN" "$CHECK_NEWER" \
+                              "$PROGRESS" "$WORKER_THREADS" "$GIT_USERNAME" "$GIT_PASSWORD" \
+                              "$CHECK_FILTER_CLASS" "$CHECK_FILTER_TYPE" "$VERIFY_CHECKSUM" "$VERBOSE"
   rm -f /tmp/distro-tool.py
 }
 
 while [ : ]; do
-  [ -z "$1" ] && break
+  [ "$1" = "" ] && break
   case $1 in
     -d|--download)
       shift
@@ -992,7 +992,7 @@ while [ : ]; do
       ;;
     -T|--threads)
       shift
-      [ $1 -gt 0 ] && WORKER_THREADS=$1
+      [ "$1" -gt 0 ] && WORKER_THREADS=$1
       ;;
     -U|--gituser)
       shift
@@ -1027,49 +1027,49 @@ while [ : ]; do
   shift
 done
 
-[ -n "${PACKAGE}" -a ${VERBOSE} -eq 0 ] && VERBOSE=1
+[ "$PACKAGE" != "" -a "$VERBOSE" -eq 0 ] && VERBOSE=1
 
-if [ ${DOGIT} = yes ]; then
+if [ "$DOGIT" = yes ]; then
   (
-    if [ -d ${LIBREELEC_DIR}/.git ]; then
-      cd ${LIBREELEC_DIR}
+    if [ -d "$LIBREELEC_DIR"/.git ]; then
+      cd "$LIBREELEC_DIR"
       git pull
     else
-      mkdir -p $(dirname "${LIBREELEC_DIR}") 2>/dev/null
-      cd $(dirname "${LIBREELEC_DIR}")
-      git clone https://github.com/LibreELEC/LibreELEC.tv.git $(basename "${LIBREELEC_DIR}")
+      mkdir -p "$(dirname "$LIBREELEC_DIR")" 2>/dev/null
+      cd "$(dirname "$LIBREELEC_DIR")"
+      git clone https://github.com/LibreELEC/LibreELEC.tv.git "$(basename "$LIBREELEC_DIR")"
     fi
   )
 fi
 
 check_exists LIBREELEC_DIR || exit
-LIBREELEC_DIR="$(get_abs_path "${LIBREELEC_DIR}")"
+LIBREELEC_DIR="$(get_abs_path "$LIBREELEC_DIR")"
 
 DISTRO_SOURCE="$(get_libreelec_option DISTRO_SRC)"
 DISTRO_MIRROR="$(get_libreelec_option DISTRO_MIRROR)"
 LIBREELEC_VER="$(get_libreelec_option LIBREELEC_VERSION)"
 
-if [ ${IS_MIRROR} = no ]; then
+if [ "$IS_MIRROR" = no ]; then
   TARGET_DIR="$(get_abs_path "${TARGET_DIR}/${LIBREELEC_VER}")"
 else
   TARGET_DIR="$(get_abs_path "${TARGET_DIR}/mirror")"
 fi
 check_exists TARGET_DIR || exit
 
-if [ ${IS_MIRROR} = no ]; then
+if [ "$IS_MIRROR" = no ]; then
   DOWNLOAD_DIR="$(get_abs_path "${DOWNLOAD_DIR}/${LIBREELEC_VER}")"
 else
   DOWNLOAD_DIR="$(get_abs_path "${DOWNLOAD_DIR}/mirror")"
 fi
 check_exists DOWNLOAD_DIR || exit
 
-if [ -n "${REVISION}" -a -z "${PACKAGE}" ]; then
+if [ "$REVISION" != "" -a -z "$PACKAGE" ]; then
   echo "ERROR: A single package must be specified with custom revision"
   exit 1
 fi
 
 echo
-if [ ${IS_MIRROR} = yes ]; then
+if [ "$IS_MIRROR" = yes ]; then
   echo "Synchronising LibreELEC.tv (branch: $(get_libreelec_branch), version: ${LIBREELEC_VER}) with MIRROR server ${TARGET_DIR}"
 else
   echo "Synchronising LibreELEC.tv (branch: $(get_libreelec_branch), version: ${LIBREELEC_VER}) with SOURCE server ${TARGET_DIR}"
@@ -1079,19 +1079,19 @@ echo "Distro Source is: ${DISTRO_SOURCE}"
 echo "Distro Mirror is: ${DISTRO_MIRROR}"
 echo " Syncing against: ${TARGET_DIR}"
 echo "  Downloading to: ${DOWNLOAD_DIR}"
-if [ -n "${PATH_FILTER}" ]; then
+if [ "$PATH_FILTER" != "" ]; then
   echo "     Path filter: ${PATH_FILTER}"
 fi
 echo "     Check Newer: ${CHECK_NEWER^}  Class/Type: ${CHECK_FILTER_CLASS} / ${CHECK_FILTER_TYPE}"
 echo "         Dry run: ${DRY_RUN^}"
-if [ ${VERBOSE} -gt 2 ]; then
+if [ "$VERBOSE" -gt 2 ]; then
   echo " Debugging level: ${VERBOSE} (${DEBUG_LOG})"
   echo "  Worker Threads: ${WORKER_THREADS}"
 fi
 echo
 
-if [ ${VERBOSE} -gt 2 -a -n "${DEBUG_LOG}" ]; then
-  generate_work "${PACKAGE}" "${REVISION}" "${PATH_FILTER}" | exec_worker_prog 2>${DEBUG_LOG}
+if [ "$VERBOSE" -gt 2 -a -n "$DEBUG_LOG" ]; then
+  generate_work "$PACKAGE" "$REVISION" "$PATH_FILTER" | exec_worker_prog 2>"$DEBUG_LOG"
 else
-  generate_work "${PACKAGE}" "${REVISION}" "${PATH_FILTER}" | exec_worker_prog
+  generate_work "$PACKAGE" "$REVISION" "$PATH_FILTER" | exec_worker_prog
 fi
diff --git a/tools/pkgcheck b/tools/pkgcheck
--- a/tools/pkgcheck
+++ b/tools/pkgcheck
@@ -16,25 +16,25 @@ log() {
   local filename="$1" lc=$2 level="$3" msg="$4" data="$5"
   local txcolour flc colw
 
-  [ "${level}" = "FAIL" ] && txcolour="${TXRED}" || txcolour="${TXYELLOW}"
+  [ "$level" = "FAIL" ] && txcolour="$TXRED" || txcolour="$TXYELLOW"
   [[ ${filename} =~ ^\./ ]] && filename="${filename:2}"
-  [ ${lc} -eq 0 ] && flc="---" || flc="$(printf "%03d" ${lc})"
+  [ "$lc" -eq 0 ] && flc="---" || flc="$(printf "%03d" "$lc")"
   [[ ${filename} =~ packages/addons/addon-depends ]] && colw=80 || colw=50
 
-  printf "[%s] %3s: %-*s: %-25s: %s\n" "${txcolour}${level}${TXRESET}" "${flc}" ${colw} "${filename}" "${msg}" "${data}"
+  printf "[%s] %3s: %-*s: %-25s: %s\n" "${txcolour}${level}${TXRESET}" "$flc" "$colw" "$filename" "$msg" "$data"
 }
 
 process_line() {
   local filename="$1" lc="$2" line="$3" inassign="$4" funcname="$5"
   local var matches assignallowed=Y
 
-  if [ -n "${funcname}" -a "${funcname}" != "configure_package" -a "${inassign}" = "Y" ]; then
+  if [ "$funcname" != "" -a "$funcname" != "configure_package" -a "$inassign" = "Y" ]; then
     if [[ ${line} =~ PKG_DEPENDS_.*= ]]; then
-      log "${filename}" ${lc} "WARN" "ignored depends assign" "${funcname}() => ${line//[[:space:]]*PKG_DEPENDS_/PKG_DEPENDS_}"
+      log "$filename" "$lc" "WARN" "ignored depends assign" "${funcname}() => ${line//[[:space:]]*PKG_DEPENDS_/PKG_DEPENDS_}"
     fi
   fi
 
-  [ -n "${funcname}" ] && return 0
+  [ "$funcname" != "" ] && return 0
 
   rightside="${line#*=}"
 
@@ -56,11 +56,11 @@ process_line() {
              ; do
 
     # After PKG_DIR, treat assigns to var as invalid
-    [ "${var}" = "PKG_DIR" ] && assignallowed=N
+    [ "$var" = "PKG_DIR" ] && assignallowed=N
 
-    if [ "${assignallowed}" = "N" ]; then
+    if [ "$assignallowed" = "N" ]; then
       if [[ ${line} =~ (^|[[:space:]])${var}= ]]; then
-        [ "${inassign}" = "N" ] && matches+=", assign to ${var}"
+        [ "$inassign" = "N" ] && matches+=", assign to ${var}"
       fi
     fi
 
@@ -73,7 +73,7 @@ process_line() {
     fi
   done
 
-  [ -n "${matches}" ] && log "${filename}" ${lc} "FAIL" "late binding violation" "${matches:2}"
+  [ "$matches" != "" ] && log "$filename" "$lc" "FAIL" "late binding violation" "${matches:2}"
 }
 
 init_target_funcs() {
@@ -99,14 +99,14 @@ check_func_name() {
            pre_unpack unpack post_unpack \
            pre_patch post_patch \
            pre_configure \
-           ${TARGET_FUNCS} \
+           "$TARGET_FUNCS" \
            pre_install post_install \
            addon post_install_addon \
            ; do
     [[ ${line} =~ ^${f} ]] && return 0
   done
 
-  log "${filename}" ${lc} "WARN" "unknown function" "${line// *{*/}"
+  log "$filename" "$lc" "WARN" "unknown function" "$line"
 }
 
 process_pkg() {
@@ -118,48 +118,48 @@ process_pkg() {
     [[ ${line} =~ ^[[:space:]]*$ ]] && continue
     [[ ${line} =~ ^(|[[:space:]]*)# ]] && continue
 
-    if [[ "${line}" =~ ^[^#]*\(\)[[:space:]]*$ ]]; then
-      log "${filename}" ${lc} "FAIL" "bad func - missing brace" "${line}"
+    if [[ "$line" =~ ^[^#]*\(\)[[:space:]]*$ ]]; then
+      log "$filename" "$lc" "FAIL" "bad func - missing brace" "$line"
     fi
 
-    if [[ "${line}" =~ \(\)[[:space:]]*\{ ]]; then
+    if [[ "$line" =~ \(\)[[:space:]]*\{ ]]; then
       funcname="${line//(*/}"
       fc=$((fc+1))
-      check_func_name "${filename}" "${lc}" "${line}"
+      check_func_name "$filename" "$lc" "$line"
     fi
 
-    if [ "${intertwined}" = "N" -a -z "${funcname}" -a ${fc} -ge 1 ]; then
-      log "${filename}" ${lc} "WARN" "intertwined vars & funcs" "${line}"
+    if [ "$intertwined" = "N" -a -z "$funcname" -a "$fc" -ge 1 ]; then
+      log "$filename" "$lc" "WARN" "intertwined vars & funcs" "$line"
       intertwined=Y
     fi
 
-    [[ "${line}" =~ ^[[:space:]]*PKG_.*=\" ]] && isassign=Y
+    [[ "$line" =~ ^[[:space:]]*PKG_.*=\" ]] && isassign=Y
 
-    process_line "$1" "${lc}" "${line}" "${isassign}" "${funcname}"
+    process_line "$1" "$lc" "$line" "$isassign" "$funcname"
 
-    [[ "${line}" =~ (\"$|\"[[:space:]]*$|\"[[:space:]]*#.*$) ]] && isassign=N
-    [[ "${line}" =~ (^}|^[[:space:]]*}) ]] && funcname=
-  done < "${filename}"
+    [[ "$line" =~ (\"$|\"[[:space:]]*$|\"[[:space:]]*#.*$) ]] && isassign=N
+    [[ "$line" =~ (^}|^[[:space:]]*}) ]] && funcname=
+  done < "$filename"
 
   # Duplicate function check
   while read -r count line; do
-    [ -n "${line}" ] && log "${filename}" 0 "FAIL" "duplicate function def" "${line}"
-  done <<< "$(grep -E ".*() {" "${filename}" | sed 's/[[:space:]]*{.*//' | sort | uniq -c | grep -v ^[[:space:]]*1[[:space:]])"
+    [ "$line" != "" ] && log "$filename" 0 "FAIL" "duplicate function def" "$line"
+  done <<< "$(grep -E ".*() {" "$filename" | sed 's/[[:space:]]*{.*//' | sort | uniq -c | grep -v ^[[:space:]]*1[[:space:]])"
 }
 
 TARGET_FUNCS="$(init_target_funcs)"
 
 if [ $# -ne 0 ]; then
-  for arg in ${@}; do
-    for p in $(find packages projects -type f -path */${arg}/package.mk | sort); do
+  for arg in "${@}"; do
+    for p in "$(find packages projects -type f -path */"$arg"/package.mk | sort)"; do
       echo -en "${TXCLR}${p}...\r" >&2
-      process_pkg "${p}"
+      process_pkg "$p"
     done
   done
 else
-  for p in $(find packages projects -type f -name package.mk | sort); do
+  for p in "$(find packages projects -type f -name package.mk | sort)"; do
     echo -en "${TXCLR}${p}...\r" >&2
-    process_pkg "${p}"
+    process_pkg "$p"
   done
 fi
-echo -en "${TXCLR}" >&2
+echo -en "$TXCLR" >&2
diff --git a/tools/update-scan b/tools/update-scan
--- a/tools/update-scan
+++ b/tools/update-scan
@@ -20,17 +20,17 @@ github_api="no"
 
 test_github_api() {
 # check for github user and token present at ~/.libreelec/options to activate github api checks
-  if [[ -n "${github_token}" || -n "${github_user}" ]]; then
+  if [[ -n "$github_token" || -n "$github_user" ]]; then
     github_api_token="-u ${github_user}:${github_token}"
     # check if token works
-    if curl -m 5 -sL -I "${github_api_token}" https://api.github.com/user | grep -q -e "^[Ss]tatus: 200" -e "^HTTP/2 200"; then
+    if curl -m 5 -sL -I "$github_api_token" https://api.github.com/user | grep -q -e "^[Ss]tatus: 200" -e "^HTTP/2 200"; then
       echo "Github api usage activated"
       github_api="yes"
     else
       message="\n your Github token is not working\n"
       message+=" github_token=${github_token}\n"
       message+=" github_user=${github_user}\n"
-      die "${message}"
+      die "$message"
     fi
   else
     message="\n | Github API not in use. Some features are disabled.\n"
@@ -39,7 +39,7 @@ test_github_api() {
     message+=" | Add your token and username to ~/.libreelec/options\n"
     message+=" | github_token=\"your_github_token_here\"\n"
     message+=" | github_user=\"your_github_username_here\"\n"
-    echo -e "${message}"
+    echo -e "$message"
   fi
 }
 
@@ -47,33 +47,33 @@ check_for_update() {
   local PKG_NAME PKG_URL PKG_VERSION RMO_API_RESPONSE GH_API_TAG
 
   # source variables from package.mk
-  PKG_NAME="$(grep -oP -m 1 '(?<=PKG_NAME=\").*(?=\")' ${1} || true)"
-  PKG_VERSION="$(grep -oP -m 1 '(?<=PKG_VERSION=\").*(?=\")' ${1} || true)"
-  eval PKG_URL="$(grep -oP -m 1 '(?<=PKG_URL=\").*(?=\")' ${1} || true)"
+  PKG_NAME="$(grep -oP -m 1 '(?<=PKG_NAME=\").*(?=\")' "${1}" || true)"
+  PKG_VERSION="$(grep -oP -m 1 '(?<=PKG_VERSION=\").*(?=\")' "${1}" || true)"
+  eval PKG_URL="$(grep -oP -m 1 '(?<=PKG_URL=\").*(?=\")' "${1}" || true)"
 
   # check if version and url are empty or self hosted by us and ignore those packages
-  if [ -z "${PKG_VERSION}" ] || [[ ${PKG_VERSION} == '$(get_pkg_version '* ]] || [ -z "${PKG_URL}" ] || [[ "${PKG_URL}" == "$DISTRO_SRC"* ]]; then
+  if [ "$PKG_VERSION" = "" ] || [[ ${PKG_VERSION} == '$(get_pkg_version '* ]] || [ "$PKG_URL" = "" ] || [[ "$PKG_URL" == "$DISTRO_SRC"* ]]; then
     PACKAGES_IGNORED+="${PKG_NAME} "
     return
   fi
 
   upstream_version=""
 
-  if [[ "${github_api}" = "yes" ]]; then
+  if [[ "$github_api" = "yes" ]]; then
     case ${PKG_NAME} in
       aspnet6-runtime)
-        upstream_version="$(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.prerelease==false) | select(.tag_name | match("v6.0")) | .tag_name][0] | sub("v";"")')"
+        upstream_version="$(curl -m 5 -sL "$github_api_token" https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.prerelease==false) | select(.tag_name | match("v6.0")) | .tag_name][0] | sub("v";"")')"
         ;;
       aspnet8-runtime)
-        upstream_version="$(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.tag_name | match("v8.0")) | .tag_name][0] | sub("v";"")')"
+        upstream_version="$(curl -m 5 -sL "$github_api_token" https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.tag_name | match("v8.0")) | .tag_name][0] | sub("v";"")')"
         ;;
     esac
   fi
 
-  if [ -z "${upstream_version}" ]; then
+  if [ "$upstream_version" = "" ]; then
     # check if package exists at tracker
     RMO_API_RESPONSE=$(curl -m 5 -sL "https://release-monitoring.org/api/project/LibreELEC/${PKG_NAME}" || true)
-    upstream_version=$(echo "${RMO_API_RESPONSE}" | jq -r '.version' || true)
+    upstream_version=$(echo "$RMO_API_RESPONSE" | jq -r '.version' || true)
 
     # special handling based on release-monitoring formatting
     case ${PKG_NAME} in
@@ -86,34 +86,34 @@ check_for_update() {
   # if pkg_version is a githash on github and github api available - always check against latest
   if [[ ${PKG_VERSION} =~ ^[a-z0-9]{40} ]] &&
     [[ ${PKG_URL} =~ ^.*(github\.com).*$ ]] &&
-    [[ "${github_api}" = "yes" ]]; then
+    [[ "$github_api" = "yes" ]]; then
 
-    github_repos=$(echo "${PKG_URL}" | grep -oP '(?<=https:\/\/github.com\/)?[0-9A-Za-z._-]+\/[0-9A-Za-z._-]+(?=/archive|/tags|/releases)')
-    le_master_version_date="Commit date: $(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/${github_repos}/git/commits/${PKG_VERSION} | jq -r '.committer.date')"
-    upstream_default_branch=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}" | jq -r '.default_branch')
-    upstream_latest_commit=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}/git/refs/heads/${upstream_default_branch}" | jq -r '.object.url')
-    upstream_latest_commit_date=$(curl -m 5 -sL "${github_api_token}" "${upstream_latest_commit}" | jq -r '.committer.date')
-    GH_API_TAG=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}/tags")
-    upstream_latest_tag=$(echo "${GH_API_TAG}" | jq -r '.[0].name')
-    upstream_latest_tag_url=$(echo "${GH_API_TAG}" | jq -r '.[0].commit.url')
-    upstream_latest_tag_date=$(curl -m 5 -sL "${github_api_token}" "${upstream_latest_tag_url}" | jq -r '.commit.committer.date')
+    github_repos=$(echo "$PKG_URL" | grep -oP '(?<=https:\/\/github.com\/)?[0-9A-Za-z._-]+\/[0-9A-Za-z._-]+(?=/archive|/tags|/releases)')
+    le_master_version_date="Commit date: $(curl -m 5 -sL "$github_api_token" https://api.github.com/repos/"$github_repos/git/commits/$PKG_VERSION" | jq -r '.committer.date')"
+    upstream_default_branch=$(curl -m 5 -sL "$github_api_token" "https://api.github.com/repos/${github_repos}" | jq -r '.default_branch')
+    upstream_latest_commit=$(curl -m 5 -sL "$github_api_token" "https://api.github.com/repos/${github_repos}/git/refs/heads/${upstream_default_branch}" | jq -r '.object.url')
+    upstream_latest_commit_date=$(curl -m 5 -sL "$github_api_token" "$upstream_latest_commit" | jq -r '.committer.date')
+    GH_API_TAG=$(curl -m 5 -sL "$github_api_token" "https://api.github.com/repos/${github_repos}/tags")
+    upstream_latest_tag=$(echo "$GH_API_TAG" | jq -r '.[0].name')
+    upstream_latest_tag_url=$(echo "$GH_API_TAG" | jq -r '.[0].commit.url')
+    upstream_latest_tag_date=$(curl -m 5 -sL "$github_api_token" "$upstream_latest_tag_url" | jq -r '.commit.committer.date')
 
     # compare upstream with local version
-    if [ "${PKG_VERSION}" != "${upstream_latest_commit##*/}" ]; then
+    if [ "$PKG_VERSION" != "${upstream_latest_commit##*/}" ]; then
       # get upstream tag informations
-      if [ "${upstream_latest_tag}" != "null" ]; then
+      if [ "$upstream_latest_tag" != "null" ]; then
         tag=" | TAG: ${upstream_latest_tag} (${upstream_latest_tag_date%T*})"
       else
         tag=" | TAG: no tags"
       fi
-      [[ "${upstream_version}" = "null" ]] && upstream_version="" || upstream_version+=" | "
+      [[ "$upstream_version" = "null" ]] && upstream_version="" || upstream_version+=" | "
       upstream_version="${upstream_version}GitHead: ${upstream_latest_commit_date%T*}${tag}"
       PKG_VERSION="${le_master_version_date%T*} | ${PKG_VERSION:0:7}"
     else
       upstream_version="${upstream_latest_commit##*/}"
     fi
-  elif [ "${upstream_version}" = "null" ]; then
-    if [[ $(echo "${RMO_API_RESPONSE}" | jq -r '.error') =~ "No package" ]]; then
+  elif [ "$upstream_version" = "null" ]; then
+    if [[ $(echo "$RMO_API_RESPONSE" | jq -r '.error') =~ "No package" ]]; then
       # package is not on tracker or github
       PACKAGES_NOT_REGISTERED+="${PKG_NAME} "
       return
@@ -124,10 +124,10 @@ check_for_update() {
   fi
 
   # print version output line
-  if [ ! -z "${API}" ]; then
-    printf "%s %s %s" "${PKG_NAME}" "${PKG_VERSION}" "${upstream_version}"; printf '\n'
-  elif [ "${PKG_VERSION}" != "${upstream_version}" ]; then
-    printf "%-35s | %-40s | %-20s" "${PKG_NAME}" "${PKG_VERSION}" "${upstream_version}"; printf '\n'
+  if [ ! -z "$API" ]; then
+    printf "%s %s %s" "$PKG_NAME" "$PKG_VERSION" "$upstream_version"; printf '\n'
+  elif [ "$PKG_VERSION" != "$upstream_version" ]; then
+    printf "%-35s | %-40s | %-20s" "$PKG_NAME" "$PKG_VERSION" "$upstream_version"; printf '\n'
   else
     PACKAGES_CURRENT+="${PKG_NAME} "
   fi
@@ -135,9 +135,9 @@ check_for_update() {
 
 
 # create list of packages
-if [ -n "${1}" ]; then
-  PACKAGE_LIST="$(find packages/ -type d -name ${1})/package.mk"
-  if [ ! -f "${PACKAGE_LIST}" ]; then
+if [ "${1}" != "" ]; then
+  PACKAGE_LIST="$(find packages/ -type d -name "${1}")/package.mk"
+  if [ ! -f "$PACKAGE_LIST" ]; then
     die "Package not found: ${1}"
   fi
 else
@@ -150,31 +150,31 @@ else
     )"
 fi
 
-if [ -z "${API}" ]; then
+if [ "$API" = "" ]; then
   # test github api availability
   test_github_api
 
   # output
   echo -e "\nUpdates found:\n"
   printf "%-35s | %-40s | %-20s" "Package" "LE git master" "upstream location"; printf '\n'
-  echo -e ''$_{1..140}'\b-'
+  echo -e ''"$_"{1..140}'\b-'
 
-  for check_version in ${PACKAGE_LIST}; do
-    check_for_update "${check_version}"
+  for check_version in "$PACKAGE_LIST"; do
+    check_for_update "$check_version"
   done
 
   echo ""
-  if [ -n "${PACKAGES_CURRENT}" ]; then
-    echo -e "\nCurrent $(echo ${PACKAGES_CURRENT} | wc -w):\n${PACKAGES_CURRENT}\n"
+  if [ "$PACKAGES_CURRENT" != "" ]; then
+    echo -e "\nCurrent $(echo "$PACKAGES_CURRENT" | wc -w):\n${PACKAGES_CURRENT}\n"
   fi
-  if [ -n "${PACKAGES_IGNORED}" ]; then
-    echo -e "\nIgnored $(echo ${PACKAGES_IGNORED} | wc -w):\n${PACKAGES_IGNORED}"
+  if [ "$PACKAGES_IGNORED" != "" ]; then
+    echo -e "\nIgnored $(echo "$PACKAGES_IGNORED" | wc -w):\n${PACKAGES_IGNORED}"
   fi
-  if [ -n "${PACKAGES_NOT_REGISTERED}" ]; then
-    echo -e "\nPackages not known at tracker $(echo ${PACKAGES_NOT_REGISTERED} | wc -w):\n${PACKAGES_NOT_REGISTERED}\n"
+  if [ "$PACKAGES_NOT_REGISTERED" != "" ]; then
+    echo -e "\nPackages not known at tracker $(echo "$PACKAGES_NOT_REGISTERED" | wc -w):\n${PACKAGES_NOT_REGISTERED}\n"
   fi
 else
-  for check_version in ${PACKAGE_LIST}; do
-    check_for_update "${check_version}"
+  for check_version in "$PACKAGE_LIST"; do
+    check_for_update "$check_version"
   done
 fi
